### ISSUE TITLE
V4 TO-DO

### ISSUE THREAD

**Issue by lsaa** [lsaa/ddstats-rust#18]
- [x] fix linux build not detecting game on ceratin distros [1]
~- [ ] cache N last games and save gold splits~ moved to v5
~- [ ] make new cached data available on ws~ moved to v5
- [x] new gamemode data for ddcl submit

[1] Probably changing the TlsConnector to use rustls instead of openssl will do the trick + editing build script

needs investigation:
~- [ ] allow ddinfo custom spawnsets to be loaded through websocket. Will need a confirmation promt on the client~ moved to v5

**Comment by rotisseriechicken** [comment]
Saving last N games should allow N to be configurable; probably 75 or 100 by default
Saving last N games should probably have a "Threshhold to Save" time, which is configurable: probably 0 by default but also could be 200 or 450 or something, your call; This way people can ignore failed farms which may "skew" their average times, so they can use the averages for whatever they want, like using it to average their last loop attempts only. 
Threshhold, and N games (or just N game averages) should be sent / accessible to DDLIVE and such, like Splits are retrievable, so DDLIVE can display what the Threshhold is, and amount of games are

**Comment by rotisseriechicken** [comment]
Averages and Gold Splits perhaps should be organized or enslaved per Player ID, so other accounts and/or offline-ness doesn't muck the metric
Gold Splits should only save for V3 runs which submit successfully
Gold Splits should be configurable so they can be manually overridden

**Comment by lsaa** [comment]
@rotisseriechicken going to move the game history to v5 because the new DDCL stuff is kinda important

**Comment by lsaa** [comment]
so for this version tag only the linux fix and new ddcl stuff
